---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kiam
    component: "agent"
    release: kiam
  name: kiam-agent

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kiam
    component: "server"
    release: kiam
  name: kiam-server
