apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: kiam

commonLabels:
  app.kubernetes.io/part-of: kiam
  app.kubernetes.io/component: kiam
  team: devops

bases:
  - base

resources:
  - certificate-issuer.yaml
  - certificate.yaml
